# Generated by Django 6.0.7 on 2026-07-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบเสร็จ')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวม (บาท)')),
                ('payment_method', models.CharField(choices=[('cash', 'เงินสด'), ('transfer', 'เงินโอน/สแกนจ่าย')], default='cash', max_length=20, verbose_name='วิธีชำระเงิน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วัน-เวลาที่ทำรายการ')),
            ],
        ),
    ]
