# Generated by Django 6.0.7 on 2026-09-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_addons_order_address_order_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('gender', models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง'), ('O', 'อื่นๆ')], max_length=1, verbose_name='เพศ')),
                ('birth_date', models.DateField(verbose_name='วันเกิด (YYYY-MM-DD)')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินเดือน')),
                ('department', models.CharField(choices=[('IT', 'ไอที'), ('HR', 'บุคคล'), ('ACC', 'บัญชี'), ('MKT', 'การตลาด')], max_length=5, verbose_name='แผนก')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='รูปภาพประจำตัว')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
