# Generated by Django 6.0.7 on 2026-09-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employee_remove_book_user_delete_order_delete_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขบัญชีธนาคาร'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('kbank', 'ธนาคารกสิกรไทย (KBANK)'), ('scb', 'ธนาคารไทยพาณิชย์ (SCB)'), ('bbl', 'ธนาคารกรุงเทพ (BBL)'), ('ktb', 'ธนาคารกรุงไทย (KTB)'), ('krungsri', 'ธนาคารกรุงศรีอยุธยา (BAY)'), ('ttb', 'ธนาคารทหารไทยธนชาต (TTB)'), ('other', 'อื่นๆ')], max_length=50, null=True, verbose_name='ชื่อธนาคาร'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่ง'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'ทำงานอยู่ (Active)'), ('probation', 'ทดลองงาน (Probation)'), ('resigned', 'ลาออก (Resigned)')], default='active', max_length=20, verbose_name='สถานะพนักงาน'),
        ),
    ]
