# Generated by Django 6.0.7 on 2026-09-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_employee_address_employee_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มทำงาน'),
        ),
    ]
