# Generated by Django 6.0.7 on 2026-09-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], default='นาย', max_length=10, verbose_name='คำนำหน้าชื่อ'),
        ),
    ]
