# Generated by Django 6.0.7 on 2026-09-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_employee_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'ประจำ (Permanent)'), ('probation', 'ทดลองงาน (Probation)'), ('resigned', 'ลาออก (Resigned)')], default='active', max_length=20, verbose_name='สถานะพนักงาน'),
        ),
    ]
