# Generated by Django 6.0.7 on 2026-09-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'ไอที'), ('HR', 'บุคคล'), ('ACC', 'บัญชี'), ('MKT', 'การตลาด'), ('SALES', 'ฝ่ายขาย'), ('PURCHASE', 'จัดซื้อ'), ('CS', 'บริการลูกค้า'), ('MGMT', 'บริหาร')], max_length=20, verbose_name='แผนก'),
        ),
    ]
