# Generated by Django 6.0.7 on 2026-09-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='วัน-เดือน-ปี เกิด (YYYY-MM-DD)'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='วันที่')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='เวลาเข้างาน')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='เวลาออกงาน')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='ชั่วโมง OT')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee', verbose_name='พนักงาน')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('leave', 'ขอลาหยุด'), ('ot', 'ขอทำงานล่วงเวลา (OT)'), ('expense', 'ขอเบิกค่าใช้จ่าย')], max_length=20, verbose_name='ประเภทคำขอ')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ / รายละเอียด')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='จำนวนเงิน หรือ จำนวนชั่วโมง')),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่งคำขอ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee', verbose_name='พนักงาน')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='เดือน')),
                ('year', models.IntegerField(verbose_name='ปี')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินเดือนพื้นฐาน')),
                ('ot_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ค่า OT')),
                ('social_security', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='หักประกันสังคม (5%)')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='หักภาษี ณ ที่จ่าย')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินเดือนสุทธิ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee', verbose_name='พนักงาน')),
            ],
        ),
    ]
