# Generated by Django 6.0.7 on 2026-09-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_employee_birth_date_attendance_employeerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='ไฟล์แนบ (ใบรับรองแพทย์/ใบเสร็จ)'),
        ),
    ]
