# Generated by Django 6.0.7 on 2026-09-15 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_employeerequest_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in']},
        ),
        migrations.AlterModelOptions(
            name='employeerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
